name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Change dir
      run: |
        cd app
        npm install
        npm run build
    - name: Deploy to firebase
      run: |
        npm install
        firebase deploy 
